from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import get_db
from app.security.auth import get_current_user
from app.models.user import User
from app.services.analysis_service import analysis_service

router = APIRouter(prefix="/api/reports", tags=["Reports"])

@router.get("/{analysis_id}")
async def get_report(
    analysis_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    analysis = await analysis_service.get_by_id(db, analysis_id)
    if not analysis:
        raise HTTPException(status_code=404, detail="Analysis not found")
    if str(analysis.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized")
    
    return {
        "report_id": f"RPT-{analysis.id}",
        "analysis_id": str(analysis.id),
        "filename": analysis.original_filename,
        "file_hash": analysis.file_hash,
        "status": analysis.status.value,
        "risk_level": analysis.risk_level,
        "confidence_score": analysis.confidence_score,
        "ai_detection_score": analysis.ai_detection_score,
        "manipulation_score": analysis.manipulation_score,
        "metadata_analysis": analysis.metadata_analysis,
        "detection_indicators": analysis.detection_indicators,
        "explainability_data": analysis.explainability_data,
        "pipeline_results": analysis.pipeline_results,
        "created_at": analysis.created_at.isoformat() if analysis.created_at else None,
        "completed_at": analysis.completed_at.isoformat() if analysis.completed_at else None,
        "disclaimer": "This report is generated by AI analysis and should not be considered definitive proof of manipulation. Manual verification is recommended."
    }

@router.get("/")
async def list_reports(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    from sqlalchemy import select
    from app.models.analysis import Analysis
    result = await db.execute(
        select(Analysis).where(
            Analysis.user_id == current_user.id,
            Analysis.status == "completed"
        ).order_by(Analysis.created_at.desc())
    )
    analyses = result.scalars().all()
    return {"reports": [{"report_id": f"RPT-{a.id}", "analysis_id": str(a.id), "filename": a.original_filename, "risk_level": a.risk_level, "created_at": a.created_at.isoformat() if a.created_at else None} for a in analyses]}
